image: python:3.5

stages:
  - build
  - test
  - deploy

lint:
  stage: build
  script:
  - pip install flake8
  - python -m flake8

test:
  stage: test
  script:
  - pip install -r requirements.txt
  - python -m pytest tests/

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y --no-install-recommends ruby-dev rubygems
  - gem install dpl
  - dpl --provider=heroku --app=sir-bot-a-lot --api-key=$HEROKU_STAGING_API_KEY
  only:
  - core/main-bot-arch
