image: python:3.5

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
  - python setup.py flake8

test:
  stage: test
  script:
  - python setup.py test

doc:
  stage: test
  script:
  - pip install -r requirements_dev.txt
  - sphinx-build -nW -b html -d docs/_build/doctrees docs/ docs/_build/html
