language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"

install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements_dev.txt

script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py doc

deploy:
  provider: script
  script: curl -X POST http://readthedocs.org/build/sir-bot-a-lot
  on:
    repo: pyslackers/sir-bot-a-lot
    branch: master
    python: "3.6"
